"""Extract the 🜎 outline from Noto Sans Symbols (weight 500) and write:
   static/favicon.svg        vector favicon: the X logo (purple glyph, teal outline), transparent
   brand/favicon.html        two-tone glyph page that render.js screenshots for PNG/ICO
   brand/avatar.html         profile-picture page (three-colour variants by hash)
   data/favicon.json         path + metrics for the animated favicon script in extended_head
   brand/exports/logo-glyph-{lilac,purple,teal}.svg   vector logo files (also used by the templates)
Run: python3 brand/make-favicon.py   (needs: pip install fonttools)"""
import json, pathlib
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

root = pathlib.Path(__file__).resolve().parent.parent
font = instantiateVariableFont(TTFont(root / 'brand/fonts/NotoSansSymbols[wght].ttf'), {'wght': 500})
gs = font.getGlyphSet(); glyph = gs[font.getBestCmap()[0x1F70E]]
bp = BoundsPen(gs); glyph.draw(bp); xmin, ymin, xmax, ymax = bp.bounds
sp = SVGPathPen(gs, ntos=lambda v: ('%.1f' % v).rstrip('0').rstrip('.')); glyph.draw(sp); d = sp.getCommands()
cx, cy = (xmin + xmax) / 2, (ymin + ymax) / 2
side = max(xmax - xmin, ymax - ymin) * 1.12          # square box with 6% padding each side
vb = '%.1f %.1f %.1f %.1f' % (cx - side / 2, -(cy + side / 2), side, side)
LILAC, PURPLE, TEAL, STROKE = '#c8c7ff', '#4a3b6b', '#7fffd4', side * 0.045

(root / 'static/favicon.svg').write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}">'
    f'<path transform="scale(1,-1)" fill="{PURPLE}" stroke="{TEAL}" stroke-width="{STROKE * 2.4:.1f}" '
    f'stroke-linejoin="round" paint-order="stroke" d="{d}"/></svg>\n')
# raster page: the X logo (purple glyph, teal outline) on transparent; #solid puts it on lilac for iOS
(root / 'brand/favicon.html').write_text(
    '<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:transparent;overflow:hidden}'
    'svg{display:block;width:100vw;height:100vh}body.solid{background:' + LILAC + '}</style></head>'
    f'<body><svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}"><path transform="scale(1,-1)" fill="{PURPLE}" '
    f'stroke="{TEAL}" stroke-width="{STROKE * 2.4:.1f}" paint-order="stroke" stroke-linejoin="round" d="{d}"/></svg>'
    '<script>if(location.hash==="#solid")document.body.classList.add("solid")</script></body></html>\n')
exports = root / 'brand/exports'; exports.mkdir(exist_ok=True)
for name, colour in (('lilac', LILAC), ('purple', PURPLE), ('teal', '#7fffd4'), ('deep', '#3a2d56')):
    (exports / f'logo-glyph-{name}.svg').write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}"><path transform="scale(1,-1)" fill="{colour}" d="{d}"/></svg>\n')
# profile picture page: three-colour variants chosen by URL hash (see render.js)
(root / 'brand/avatar.html').write_text(f"""<!doctype html><html><head><meta charset="utf-8">
<!-- X profile picture, 1000 x 1000, generated by make-glyph.py. Variants by hash:
     #v-stroke  lilac ground, purple glyph, teal outline around the glyph (default X picture)
     #v-ring    lilac ground, purple glyph, teal ring near the edge
     #v-inverse purple ground, lilac glyph, teal ring and ticks -->
<style>
html,body{{margin:0;overflow:hidden}} body{{background:{LILAC};width:100vw;height:100vh}}
body.v-inverse{{background:{PURPLE}}}
svg{{display:block;width:100vw;height:100vh}}
.glyph{{fill:{PURPLE}}} body.v-inverse .glyph{{fill:{LILAC}}}
body.v-stroke .glyph{{stroke:#7fffd4;stroke-width:{STROKE * 2.4:.1f};stroke-linejoin:round;paint-order:stroke}}
.ring{{display:none;fill:none;stroke:#7fffd4;stroke-width:{side * 0.028:.1f}}}
body.v-ring .ring,body.v-inverse .ring{{display:inline}}
.tick{{display:none;stroke:#7fffd4;stroke-width:{side * 0.02:.1f}}} body.v-inverse .tick{{display:inline}}
</style></head><body>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{cx - side:.1f} {-(cy + side):.1f} {side * 2:.1f} {side * 2:.1f}">
<circle class="ring" cx="{cx:.1f}" cy="{-cy:.1f}" r="{side * 0.88:.1f}"/>
<g class="tick"><line x1="{cx:.1f}" y1="{-cy - side * 0.98:.1f}" x2="{cx:.1f}" y2="{-cy - side * 0.84:.1f}"/><line x1="{cx:.1f}" y1="{-cy + side * 0.84:.1f}" x2="{cx:.1f}" y2="{-cy + side * 0.98:.1f}"/><line x1="{cx - side * 0.98:.1f}" y1="{-cy:.1f}" x2="{cx - side * 0.84:.1f}" y2="{-cy:.1f}"/><line x1="{cx + side * 0.84:.1f}" y1="{-cy:.1f}" x2="{cx + side * 0.98:.1f}" y2="{-cy:.1f}"/></g>
<path class="glyph" transform="scale(1,-1)" d="{d}"/>
</svg>
<script>var h=location.hash.slice(1);if(h)document.body.classList.add(h)</script>
</body></html>
""")
# wallpaper tile: the glyph at 56% of a square cell (lilac), for repeating backgrounds
tile = side / 0.56
(exports / 'logo-glyph-tile.svg').write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{cx - tile/2:.1f} {-(cy + tile/2):.1f} {tile:.1f} {tile:.1f}"><path transform="scale(1,-1)" fill="{LILAC}" d="{d}"/></svg>\n')
# copies for the site (header logo, wallpaper, giant glyph)
site = root / 'static/img'; site.mkdir(parents=True, exist_ok=True)
for n in ('lilac', 'purple', 'deep', 'tile'):
    (site / f'logo-glyph-{n}.svg').write_text((exports / f'logo-glyph-{n}.svg').read_text())
(root / 'data/favicon.json').write_text(json.dumps({'d': d, 'cx': round(cx, 1), 'cy': round(cy, 1), 'side': round(side, 1), 'stroke': round(STROKE, 1)}) + '\n')
print('favicon.svg, favicon.html, favicon.json and logo-glyph-*.svg written; glyph box', round(xmax - xmin), 'x', round(ymax - ymin))
