"""Multi-colour, multi-frame pixel art in the brand's style: the animated sibling of
make-icons.py. Every sprite is a list of ASCII frames, one character per pixel:

  l lilac #c8c7ff   t teal #7fffd4    p purple #4a3b6b (page bg)   d deep #3a2d56
  k ink #241a3a     v NYU violet #57068c    w white #ffffff   . transparent

Writes, per sprite:
  layouts/partials/px/<name>.html      inline SVG, one <g class="px__f" style="--i:N"> per
                                       frame, rects carry only a colour class (l t p d k v w);
                                       the site CSS shows one frame at a time (px--n<frames>)
  brand/exports/pixelart/<name>-f<i>.svg   standalone preview per frame, real fills, purple bg
  brand/exports/pixelart/sheet.html        contact sheet, every frame at 4x
and then renders sheet.png with brand/render-pixelart.js (Playwright).
Frame order is animation order; every animation loops.
Run: python3 brand/make-pixel-art.py
"""
import pathlib
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
PALETTE = {
    'l': '#c8c7ff',  # lilac: main accent, outlines
    't': '#7fffd4',  # teal: highlights, "on" lights
    'p': '#4a3b6b',  # purple: page background
    'd': '#3a2d56',  # deep purple: sunken wells, dark body fill
    'k': '#241a3a',  # near-black purple: shadows, windows
    'v': '#57068c',  # NYU violet: title bars, accent splashes
    'w': '#ffffff',  # white: sparkles, caps
}
# name: (width, height, frames)
EXPECT = {
    'cassette': (64, 40, 8),
    'eq': (40, 16, 8),
    'easel': (48, 40, 6),
    'glyph': (24, 24, 4),
    'calendar': (32, 24, 2),
    'notes': (24, 24, 4),
    'star': (8, 8, 4),
    'disc': (32, 32, 8),
}

SPRITES = {
    # Compact cassette, 64x40. Lilac shell, label band with teal/violet stripes, ink window with
    # two reels: the left spool full (fat violet tape pack), the right nearly empty. The hub spokes
    # turn 45 degrees clockwise per frame (8 frames = one full turn); teal glints stay put.
    'cassette': [
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkllkllvvvvvvkkkkkkvtllkllkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlkkkllkkklvvvvvkkkkkvtlkkkllkkklvvkkkkkkklpppddl
lddppplkkkvvtvvvlkkkllkkklvvvvvvkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkllkkkklvvvvvkkkkvlkkkkllkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkwwkkkklvvvvvkkkkvlkkkkwwkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkklwwlkkklvvvvvkkkkvlkkklwwlkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkllllllkklvvvvvkkkkvlkkllllllkklvkkkkkkklpppddl
lddppplkkkvvvvvvllllkkllllvvvvvvkkkkvvllllkkllllvvkkkkkkklpppddl
lddppplkkkkvvvvvlllkkkklllvvvvvkkkkkvvlllkkkklllvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkkkkllvvvvvvkkkkkkvvllkkkkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkkkkllvvvvvvkkkkkkvtllkkkkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlkkkkkklllvvvvvkkkkkvtlkkkkkklllvvkkkkkkklpppddl
lddppplkkkvvtvvvlkkkkkllllvvvvvvkkkkvvlkkkkkllllvvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkklllkklvvvvvkkkkvlkkkkklllkklvkkkkkkklpppddl
lddppplkkkvvvvvlllllwwlkkklvvvvvkkkkvlllllwwlkkklvkkkkkkklpppddl
lddppplkkkvvvvvlllllwwkkkklvvvvvkkkkvlllllwwkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkllkkkklvvvvvkkkkvlkkkkllkkkklvkkkkkkklpppddl
lddppplkkkvvvvvvlkkkllkkklvvvvvvkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvlkkkllkkklvvvvvkkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkllkllvvvvvvkkkkkkvvllkllkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkkkkllvvvvvvkkkkkkvtllkkkkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlllkkkkkklvvvvvkkkkkvtlllkkkkkklvvkkkkkkklpppddl
lddppplkkkvvtvvvllllkkkkklvvvvvvkkkkvvllllkkkkklvvkkkkkkklpppddl
lddppplkkkvvvvvlkklllkkkkklvvvvvkkkkvlkklllkkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkklwwlllllvvvvvkkkkvlkkklwwlllllvkkkkkkklpppddl
lddppplkkkvvvvvlkkklwwlllllvvvvvkkkkvlkkklwwlllllvkkkkkkklpppddl
lddppplkkkvvvvvlkklllkkkkklvvvvvkkkkvlkklllkkkkklvkkkkkkklpppddl
lddppplkkkvvvvvvllllkkkkklvvvvvvkkkkvvllllkkkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvlllkkkkkklvvvvvkkkkkvvlllkkkkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkkkkllvvvvvvkkkkkkvvllkkkkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkllkllvvvvvvkkkkkkvtllkllkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlkkkllkkklvvvvvkkkkkvtlkkkllkkklvvkkkkkkklpppddl
lddppplkkkvvtvvvlkkkllkkklvvvvvvkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkllkkkklvvvvvkkkkvlkkkkllkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlllllwwkkkklvvvvvkkkkvlllllwwkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlllllwwlkkklvvvvvkkkkvlllllwwlkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkklllkklvvvvvkkkkvlkkkkklllkklvkkkkkkklpppddl
lddppplkkkvvvvvvlkkkkkllllvvvvvvkkkkvvlkkkkkllllvvkkkkkkklpppddl
lddppplkkkkvvvvvlkkkkkklllvvvvvkkkkkvvlkkkkkklllvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkkkkllvvvvvvkkkkkkvvllkkkkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkkkkllvvvvvvkkkkkkvtllkkkkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlllkkkklllvvvvvkkkkkvtlllkkkklllvvkkkkkkklpppddl
lddppplkkkvvtvvvllllkkllllvvvvvvkkkkvvllllkkllllvvkkkkkkklpppddl
lddppplkkkvvvvvlkkllllllkklvvvvvkkkkvlkkllllllkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkklwwlkkklvvvvvkkkkvlkkklwwlkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkwwkkkklvvvvvkkkkvlkkkkwwkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkllkkkklvvvvvkkkkvlkkkkllkkkklvkkkkkkklpppddl
lddppplkkkvvvvvvlkkkllkkklvvvvvvkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvlkkkllkkklvvvvvkkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkllkllvvvvvvkkkkkkvvllkllkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkllkllvvvvvvkkkkkkvtllkllkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlkkkllkkklvvvvvkkkkkvtlkkkllkkklvvkkkkkkklpppddl
lddppplkkkvvtvvvlkkkllkkklvvvvvvkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkllkkkklvvvvvkkkkvlkkkkllkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkwwlllllvvvvvkkkkvlkkkkwwlllllvkkkkkkklpppddl
lddppplkkkvvvvvlkkklwwlllllvvvvvkkkkvlkkklwwlllllvkkkkkkklpppddl
lddppplkkkvvvvvlkklllkkkkklvvvvvkkkkvlkklllkkkkklvkkkkkkklpppddl
lddppplkkkvvvvvvllllkkkkklvvvvvvkkkkvvllllkkkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvlllkkkkkklvvvvvkkkkkvvlllkkkkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkkkkllvvvvvvkkkkkkvvllkkkkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkkkkllvvvvvvkkkkkkvtllkkkkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlkkkkkklllvvvvvkkkkkvtlkkkkkklllvvkkkkkkklpppddl
lddppplkkkvvtvvvlkkkkkllllvvvvvvkkkkvvlkkkkkllllvvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkklllkklvvvvvkkkkvlkkkkklllkklvkkkkkkklpppddl
lddppplkkkvvvvvlllllwwlkkklvvvvvkkkkvlllllwwlkkklvkkkkkkklpppddl
lddppplkkkvvvvvlllllwwlkkklvvvvvkkkkvlllllwwlkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkklllkklvvvvvkkkkvlkkkkklllkklvkkkkkkklpppddl
lddppplkkkvvvvvvlkkkkkllllvvvvvvkkkkvvlkkkkkllllvvkkkkkkklpppddl
lddppplkkkkvvvvvlkkkkkklllvvvvvkkkkkvvlkkkkkklllvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkkkkllvvvvvvkkkkkkvvllkkkkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
"""
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
.lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl.
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddttttttttttttttttttttttttttttttttttttttttttttttttttttttttttddl
lddvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvttvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkvvttvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkvvtvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkvtvvvvvllllvvvvvvvkkkkkkkkvtvllllvvvkkkkkkkkklpppddl
lddppplkkkkvttvvvllkkkkllvvvvvvkkkkkkvtllkkkkllvvkkkkkkkklpppddl
lddppplkkkkvtvvvlllkkkkkklvvvvvkkkkkvtlllkkkkkklvvkkkkkkklpppddl
lddppplkkkvvtvvvllllkkkkklvvvvvvkkkkvvllllkkkkklvvkkkkkkklpppddl
lddppplkkkvvvvvlkklllkkkkklvvvvvkkkkvlkklllkkkkklvkkkkkkklpppddl
lddppplkkkvvvvvlkkklwwlllllvvvvvkkkkvlkkklwwlllllvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkwwlllllvvvvvkkkkvlkkkkwwlllllvkkkkkkklpppddl
lddppplkkkvvvvvlkkkkllkkkklvvvvvkkkkvlkkkkllkkkklvkkkkkkklpppddl
lddppplkkkvvvvvvlkkkllkkklvvvvvvkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvlkkkllkkklvvvvvkkkkkvvlkkkllkkklvvkkkkkkklpppddl
lddppplkkkkvvvvvvllkllkllvvvvvvkkkkkkvvllkllkllvvkkkkkkkklpppddl
lddppplkkkkkvvvvvvvllllvvvvvvvkkkkkkkkvvvllllvvvkkkkkkkkklpppddl
lddppplkkkkkvvvvvvvvvvvvvvvvvvkkkkkkkkkvvvvvvvvkkkkkkkkkklpppddl
lddppplkkkkkkvvvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkvvvvvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkvvvvvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkvvvvvvkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddppplkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklpppddl
lddpppllllllllllllllllllllllllllllllllllllllllllllllllllllpppddl
lddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddl
lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl
ldddddddddddddlllllllllllllllllllllllllllllllllllldddddddddddddl
lddddddddddddldddlllddddddddddddddddddddddddllldddlddddddddddddl
ldddddddddddlddddlkldddkkdddkkkkkkkkdddkkdddlklddddldddddddddddl
lddddddddddldddddllldddkkdddkkkkkkkkdddkkdddllldddddlddddddddddl
.lddddddddldddddddddddddddddkkkkkkkkdddddddddddddddddlddddddddl.
..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll..
""",
    ],
    # 10-bar spectrum analyser, 40x16: 3px teal bars, 1px gaps, white cap row. The bass pumps
    # twice per loop (peaks on frames 0 and 4), the mids roll as a wave, the highs tick on the off-beats;
    # every bar is periodic in 8 frames, so 7 -> 0 is an ordinary step.
    'eq': [
"""
........................................
........................................
www.www.................................
ttt.ttt.................................
ttt.ttt.................................
ttt.ttt.www.....www.....................
ttt.ttt.ttt.www.ttt.....................
ttt.ttt.ttt.ttt.ttt.....................
ttt.ttt.ttt.ttt.ttt.....................
ttt.ttt.ttt.ttt.ttt.www.....www.........
ttt.ttt.ttt.ttt.ttt.ttt.....ttt.www.....
ttt.ttt.ttt.ttt.ttt.ttt.....ttt.ttt.....
ttt.ttt.ttt.ttt.ttt.ttt.....ttt.ttt.www.
ttt.ttt.ttt.ttt.ttt.ttt.www.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
....www.................................
....ttt.www.............................
www.ttt.ttt.....www.....................
ttt.ttt.ttt.....ttt.....................
ttt.ttt.ttt.....ttt.www.....www.........
ttt.ttt.ttt.....ttt.ttt.....ttt.www.....
ttt.ttt.ttt.www.ttt.ttt.....ttt.ttt.....
ttt.ttt.ttt.ttt.ttt.ttt.....ttt.ttt.www.
ttt.ttt.ttt.ttt.ttt.ttt.www.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
........................................
........................................
........................................
....................www.................
................www.ttt.................
....www.www.....ttt.ttt.................
....ttt.ttt.....ttt.ttt.www.............
www.ttt.ttt.....ttt.ttt.ttt.www.........
ttt.ttt.ttt.www.ttt.ttt.ttt.ttt.........
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.www.....
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.....
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.www.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
........................................
........................................
........................................
........................................
www.www.............www.www.............
ttt.ttt.............ttt.ttt.www.........
ttt.ttt.............ttt.ttt.ttt.www.....
ttt.ttt.www.....www.ttt.ttt.ttt.ttt.www.
ttt.ttt.ttt.www.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
www.www.................................
ttt.ttt.................................
ttt.ttt.................................
ttt.ttt.................................
ttt.ttt.www.............www.............
ttt.ttt.ttt.............ttt.............
ttt.ttt.ttt.........www.ttt.............
ttt.ttt.ttt.www.....ttt.ttt.............
ttt.ttt.ttt.ttt.www.ttt.ttt.www.........
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.www.www.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
........................................
....www.................................
....ttt.................................
....ttt.www.............................
www.ttt.ttt.www.........................
ttt.ttt.ttt.ttt.........................
ttt.ttt.ttt.ttt.........www.............
ttt.ttt.ttt.ttt.........ttt.www.www.www.
ttt.ttt.ttt.ttt.www.www.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
........................................
........................................
............www.........................
............ttt.........................
............ttt.........................
....www.www.ttt.........................
....ttt.ttt.ttt.www.....................
www.ttt.ttt.ttt.ttt.....................
ttt.ttt.ttt.ttt.ttt.....www.............
ttt.ttt.ttt.ttt.ttt.www.ttt.www.www.www.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
"""
........................................
........................................
........................................
........................................
........................................
www.........www.........................
ttt.www.....ttt.www.....................
ttt.ttt.....ttt.ttt.............www.....
ttt.ttt.www.ttt.ttt.........www.ttt.www.
ttt.ttt.ttt.ttt.ttt.........ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.........ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.www.....ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.....ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.www.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.ttt.
""",
    ],
    # Easel with an ink canvas, 48x40. The brush (teal handle) paints a squiggle left to right
    # over frames 0-4; frame 5 is the finished stroke with the brush laid on the ledge.
    'easel': [
"""
......................llll......................
.....................llllll.....................
.....................lddddl.....................
........llllllllllllllddddllllllllllllll........
........lkkkkkkkkkkkklvvlllkkkkkkkkkkkkl........
........lkkkkkkkkkkkkttvkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkktttkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkktttkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkktttkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkktttkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkklllkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkklllkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkvvvkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkwvvkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkwkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkktkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkktkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkvkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........llllllllllllllllllllllllllllllll........
.....llllllllllllllllllllllllllllllllllllll.....
.....lddddddddddddddddddddddddddddddddddddl.....
.....llllllllllllllllllllllllllllllllllllll.....
.............lddl.....lddl.....lddl.............
.............lddl.....lddl.....lddl.............
............lddl......lddl......lddl............
............lddl......lddl......lddl............
...........lddl.......lddl.......lddl...........
...........lddl.......lddl.......lddl...........
..........lddl........lddl........lddl..........
..........lddl........llll........lddl..........
.........lddl......................lddl.........
.........llll......................llll.........
""",
"""
......................llll......................
.....................llllll.....................
.....................lddddl.....................
........llllllllllllllddddllllllllllllll........
........lkkkkkkkkkkkkllllllkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkvvkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkttvkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkktttkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkktttkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkktttkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkktttkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkklllkkkkkkkkkkkkkkl........
........lkkkttkkkkkkklllkkkkkkkkkkkkkkkl........
........lkkkttkkkkkkvvvkkkkkkkkkkkkkkkkl........
........lkkktttkkkkwvvkkkkkkkkkkkkkkkkkl........
........lkkkvtttkkwkkkkkkkkkkkkkkkkkkkkl........
........lkkkkttttttkkkkkkkkkkkkkkkkkkkkl........
........lkkkkvtttttkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkvtttvkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkvvvvkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........llllllllllllllllllllllllllllllll........
.....llllllllllllllllllllllllllllllllllllll.....
.....lddddddddddddddddddddddddddddddddddddl.....
.....llllllllllllllllllllllllllllllllllllll.....
.............lddl.....lddl.....lddl.............
.............lddl.....lddl.....lddl.............
............lddl......lddl......lddl............
............lddl......lddl......lddl............
...........lddl.......lddl.......lddl...........
...........lddl.......lddl.......lddl...........
..........lddl........lddl........lddl..........
..........lddl........llll........lddl..........
.........lddl......................lddl.........
.........llll......................llll.........
""",
"""
......................llll........vv............
.....................llllll......ttv............
.....................lddddl.....ttt.............
........llllllllllllllddddllllltttllllll........
........lkkkkkkkkkkkkllllllkkktttkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkktttkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkklllkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkklllkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkvvvkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkwvvkkkkkkkkkkkl........
........lkkkkkkkkkkkkkktwkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkktttkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkttttkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkttvvkkkkkkkkkkkkkkl........
........lkkkttkkkkkkttvvkkkkkkkkkkkkkkkl........
........lkkkttkkkkkttvvkkkkkkkkkkkkkkkkl........
........lkkktttkkkktttkkkkkkkkkkkkkkkkkl........
........lkkkvtttkkttvvkkkkkkkkkkkkkkkkkl........
........lkkkkttttttvvkkkkkkkkkkkkkkkkkkl........
........lkkkkvttttttkkkkkkkkkkkkkkkkkkkl........
........lkkkkkvtttvvkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkvvvvkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........llllllllllllllllllllllllllllllll........
.....llllllllllllllllllllllllllllllllllllll.....
.....lddddddddddddddddddddddddddddddddddddl.....
.....llllllllllllllllllllllllllllllllllllll.....
.............lddl.....lddl.....lddl.............
.............lddl.....lddl.....lddl.............
............lddl......lddl......lddl............
............lddl......lddl......lddl............
...........lddl.......lddl.......lddl...........
...........lddl.......lddl.......lddl...........
..........lddl........lddl........lddl..........
..........lddl........llll........lddl..........
.........lddl......................lddl.........
.........llll......................llll.........
""",
"""
......................llll......................
.....................llllll.....................
.....................lddddl.....................
........llllllllllllllddddllllllllllllll........
........lkkkkkkkkkkkkllllllkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkvv.......
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkttv.......
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkttt........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkktttl........
........lkkkkkkkkkkkkkktwttkkkkkkkktttkl........
........lkkkkkkkkkkkkktttttkkkkkkktttkkl........
........lkkkkkkkkkkkktttttttkkkkklllkkkl........
........lkkkkkkkkkkkkttvvvtttkkklllkkkkl........
........lkkkttkkkkkkttvvkktttkkvvvkkkkkl........
........lkkkttkkkkkttvvkkkvtttwvvkkkkkkl........
........lkkktttkkkktttkkkkkvtwkkkkkkkkkl........
........lkkkvtttkkttvvkkkkkkttkkkkkkkkkl........
........lkkkkttttttvvkkkkkkkvtkkkkkkkkkl........
........lkkkkvttttttkkkkkkkkkvkkkkkkkkkl........
........lkkkkkvtttvvkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkvvvvkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........llllllllllllllllllllllllllllllll........
.....llllllllllllllllllllllllllllllllllllll.....
.....lddddddddddddddddddddddddddddddddddddl.....
.....llllllllllllllllllllllllllllllllllllll.....
.............lddl.....lddl.....lddl.............
.............lddl.....lddl.....lddl.............
............lddl......lddl......lddl............
............lddl......lddl......lddl............
...........lddl.......lddl.......lddl...........
...........lddl.......lddl.......lddl...........
..........lddl........lddl........lddl..........
..........lddl........llll........lddl..........
.........lddl......................lddl.........
.........llll......................llll.........
""",
"""
......................llll......................
.....................llllll.....................
.....................lddddl.....................
........llllllllllllllddddllllllllllllll........
........lkkkkkkkkkkkkllllllkkkkkkkkkkkkl.....vv.
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl....ttv.
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl...ttt..
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl..ttt...
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl.ttt....
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklttt.....
........lkkkkkkkkkkkkkktwttkkkkkkkkkkkklll......
........lkkkkkkkkkkkkktttttkkkkkkkkkkklll.......
........lkkkkkkkkkkkktttttttkkkkkkkkkvvv........
........lkkkkkkkkkkkkttvvvtttkkkkkkkwvvl........
........lkkkttkkkkkkttvvkktttkkkkkkwkkkl........
........lkkkttkkkkkttvvkkkvtttkkkkktkkkl........
........lkkktttkkkktttkkkkkvtttkkkttkkkl........
........lkkkvtttkkttvvkkkkkktttkkttvkkkl........
........lkkkkttttttvvkkkkkkkvtttttttkkkl........
........lkkkkvttttttkkkkkkkkkvttttvvkkkl........
........lkkkkkvtttvvkkkkkkkkkktttvvkkkkl........
........lkkkkkkvvvvkkkkkkkkkkkvvvvkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........llllllllllllllllllllllllllllllll........
.....llllllllllllllllllllllllllllllllllllll.....
.....lddddddddddddddddddddddddddddddddddddl.....
.....llllllllllllllllllllllllllllllllllllll.....
.............lddl.....lddl.....lddl.............
.............lddl.....lddl.....lddl.............
............lddl......lddl......lddl............
............lddl......lddl......lddl............
...........lddl.......lddl.......lddl...........
...........lddl.......lddl.......lddl...........
..........lddl........lddl........lddl..........
..........lddl........llll........lddl..........
.........lddl......................lddl.........
.........llll......................llll.........
""",
"""
......................llll......................
.....................llllll.....................
.....................lddddl.....................
........llllllllllllllddddllllllllllllll........
........lkkkkkkkkkkkkllllllkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkktwttkkkkkkkkkkkkl........
........lkkkkkkkkkkkkktttttkkkkkkkkkkkkl........
........lkkkkkkkkkkkktttttttkkkkkkkkkkkl........
........lkkkkkkkkkkkkttvvvtttkkkkkkkkkkl........
........lkkkttkkkkkkttvvkktttkkkkkktkkkl........
........lkkkttkkkkkttvvkkkvtttkkkkktkkkl........
........lkkktttkkkktttkkkkkvtttkkkttkkkl........
........lkkkvtttkkttvvkkkkkktttkkttvkkkl........
........lkkkkttttttvvkkkkkkkvtttttttkkkl........
........lkkkkvttttttkkkkkkkkkvttttvvkkkl........
........lkkkkkvtttvvkkkkkkkkkktttvvkkkkl........
........lkkkkkkvvvvkkkkkkkkkkkvvvvkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl........
........lkkkkkkkkkkkkkkkkkkkkkkvvlllttttttttttt.
........lllllllllllllllllllllwvvvlllttttttttttv.
.....llllllllllllllllllllllllllllllllllllll.....
.....lddddddddddddddddddddddddddddddddddddl.....
.....llllllllllllllllllllllllllllllllllllll.....
.............lddl.....lddl.....lddl.............
.............lddl.....lddl.....lddl.............
............lddl......lddl......lddl............
............lddl......lddl......lddl............
...........lddl.......lddl.......lddl...........
...........lddl.......lddl.......lddl...........
..........lddl........lddl........lddl..........
..........lddl........llll........lddl..........
.........lddl......................lddl.........
.........llll......................llll.........
""",
    ],
    # The brand glyph (static/img/logo-glyph-lilac.svg) at 24px: 2px stem and bars, 3px runs on
    # the diagonals for the same optical weight. The stroke breathes lilac -> teal -> white -> teal.
    'glyph': [
"""
...........ll...........
...........ll...........
..........llll..........
.........llllll.........
.........llllll.........
........lll..lll........
.......lll....lll.......
.......lll....lll.......
......lll......lll......
.....lll........lll.....
.....lll........lll.....
....lll..........lll....
...lll............lll...
...llllllllllllllllll...
..llllllllllllllllllll..
........llllllll........
.......lll.ll.lll.......
......lll..ll..lll......
......lll..ll..lll......
.....lll...ll...lll.....
....lll....ll....lll....
...lll.....ll.....lll...
..lllll..llllll..lllll..
..lllll..llllll..lllll..
""",
"""
...........tt...........
...........tt...........
..........tttt..........
.........tttttt.........
.........tttttt.........
........ttt..ttt........
.......ttt....ttt.......
.......ttt....ttt.......
......ttt......ttt......
.....ttt........ttt.....
.....ttt........ttt.....
....ttt..........ttt....
...ttt............ttt...
...tttttttttttttttttt...
..tttttttttttttttttttt..
........tttttttt........
.......ttt.tt.ttt.......
......ttt..tt..ttt......
......ttt..tt..ttt......
.....ttt...tt...ttt.....
....ttt....tt....ttt....
...ttt.....tt.....ttt...
..ttttt..tttttt..ttttt..
..ttttt..tttttt..ttttt..
""",
"""
...........ww...........
...........ww...........
..........wwww..........
.........wwwwww.........
.........wwwwww.........
........www..www........
.......www....www.......
.......www....www.......
......www......www......
.....www........www.....
.....www........www.....
....www..........www....
...www............www...
...wwwwwwwwwwwwwwwwww...
..wwwwwwwwwwwwwwwwwwww..
........wwwwwwww........
.......www.ww.www.......
......www..ww..www......
......www..ww..www......
.....www...ww...www.....
....www....ww....www....
...www.....ww.....www...
..wwwww..wwwwww..wwwww..
..wwwww..wwwwww..wwwww..
""",
"""
...........tt...........
...........tt...........
..........tttt..........
.........tttttt.........
.........tttttt.........
........ttt..ttt........
.......ttt....ttt.......
.......ttt....ttt.......
......ttt......ttt......
.....ttt........ttt.....
.....ttt........ttt.....
....ttt..........ttt....
...ttt............ttt...
...tttttttttttttttttt...
..tttttttttttttttttttt..
........tttttttt........
.......ttt.tt.ttt.......
......ttt..tt..ttt......
......ttt..tt..ttt......
.....ttt...tt...ttt.....
....ttt....tt....ttt....
...ttt.....tt.....ttt...
..ttttt..tttttt..ttttt..
..ttttt..tttttt..ttttt..
""",
    ],
    # Wall calendar page, 32x24: violet header with two rings, 7x4 day cells, teal "today",
    # ink drop shadow. The header cursor blinks (on in frame 0, off in frame 1).
    'calendar': [
"""
....ll...................ll.....
...l..l.................l..l....
lllllllllllllllllllllllllllllll.
lvvlvvlvvvvvvvvvvvvvvvvvlvvlvvlk
lvvlvvlvvvvvvvvvvvvllvvvlvvlvvlk
lvvvkkvvvlllvlllllvllvvvvkkvvvlk
lvvvkkvvvlllvlllllvllvvvvkkvvvlk
lvvvvvvvvvvvvvvvvvvllvvvvvvvvvlk
lvvvvvvvvvvvvvvvvvvvvvvvvvvvvvlk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddktttkdddkdddkdddklk
lkdddkdddkdddktttkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lllllllllllllllllllllllllllllllk
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
""",
"""
....ll...................ll.....
...l..l.................l..l....
lllllllllllllllllllllllllllllll.
lvvlvvlvvvvvvvvvvvvvvvvvlvvlvvlk
lvvlvvlvvvvvvvvvvvvvvvvvlvvlvvlk
lvvvkkvvvlllvlllllvvvvvvvkkvvvlk
lvvvkkvvvlllvlllllvvvvvvvkkvvvlk
lvvvvvvvvvvvvvvvvvvvvvvvvvvvvvlk
lvvvvvvvvvvvvvvvvvvvvvvvvvvvvvlk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddktttkdddkdddkdddklk
lkdddkdddkdddktttkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkdddkdddkdddkdddkdddkdddkdddklk
lkkkkkkkkkkkkkkkkkkkkkkkkkkkkklk
lllllllllllllllllllllllllllllllk
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
""",
    ],
    # Three eighth notes (one teal) rising and swaying; each note loops bottom -> top over the
    # 4 frames, staggered so one note re-enters at the bottom every frame.
    'notes': [
"""
........................
........................
........................
........................
........................
........................
............ll..........
............lll.........
............llll........
............l.ll........
............l..l....ll..
............l.......lll.
..........lll.......llll
.........llll.......l.ll
...tt....llll.......l..l
...ttt....ll........l...
...tttt...........lll...
...t.tt..........llll...
...t..t..........llll...
...t..............ll....
.ttt....................
tttt....................
tttt....................
.tt.....................
""",
"""
........................
........................
...........ll...........
...........lll..........
...........llll.........
...........l.ll.........
...........l..l.....ll..
...........l........lll.
.........lll........llll
........llll........l.ll
....tt..llll........l..l
....ttt..ll.........l...
....tttt..........lll...
....t.tt.........llll...
....t..t.........llll...
....t.............ll....
..ttt...................
.tttt...................
.tttt...................
..tt....................
........................
........................
........................
........................
""",
"""
........................
........................
...................ll...
...................lll..
...................llll.
...................l.ll.
....tt.............l..l.
....ttt............l....
....tttt.........lll....
....t.tt........llll....
....t..t........llll....
....t............ll.....
..ttt...................
.tttt...................
.tttt......ll...........
..tt.......lll..........
...........llll.........
...........l.ll.........
...........l..l.........
...........l............
.........lll............
........llll............
........llll............
.........ll.............
""",
"""
........................
........................
...tt...................
...ttt..................
...tttt.................
...t.tt.................
...t..t.................
...t....................
.ttt....................
tttt....................
tttt........ll..........
.tt.........lll.........
............llll........
............l.ll........
............l..l...ll...
............l......lll..
..........lll......llll.
.........llll......l.ll.
.........llll......l..l.
..........ll.......l....
.................lll....
................llll....
................llll....
.................ll.....
""",
    ],
    # Twinkle, 8x8: one white pixel grows into a 4-point teal sparkle and shrinks back.
    'star': [
"""
........
........
........
...w....
........
........
........
........
""",
"""
........
........
...t....
..twt...
...t....
........
........
........
""",
"""
...t....
...t....
..ttt...
tttwttt.
..ttt...
...t....
...t....
........
""",
"""
........
........
...t....
..twt...
...t....
........
........
........
""",
    ],
    # Record / CD, 32x32: lilac rim, ink disc with deep grooves, violet label, white spindle hole.
    # The teal reflection arc steps 45 degrees clockwise per frame (8 frames = one turn).
    'disc': [
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkttkkkkkkddkkkl.....
....lkkddktttttkkkkkkkkddkkl....
...lkkdkkttttkkkkkkkkkkkkdkkl...
..lkkdkktttkkddddddkkkkkkkdkkl..
..lkkdkttkkddkkkkkkddkkkkkdkkl..
.lkkdkttkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdtttkdkkkvvvvvvkkkdkkkkdkkl.
.lkdkttkdkkvvvvvvvvvvkkdkkkkdkl.
lkkdkttkdkkvvvvvvvvvvkkdkkkkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
..lkkdkkkkkkkddddddkkkkkkkdkkl..
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
....lkkddkkkkkkkkkkkkkkddkkl....
.....lkkkddkkkkkkkkkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkttttttkkddkkkl.....
....lkkddkttttttttttttkddkkl....
...lkkdkkkkttkkkkkkttttkkdkkl...
..lkkdkkkkkkkddddddkkttkkkdkkl..
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
..lkkdkkkkkkkddddddkkkkkkkdkkl..
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
....lkkddkkkkkkkkkkkkkkddkkl....
.....lkkkddkkkkkkkkkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkkkkkkkkkddkkkl.....
....lkkddkkkkkkkkkktttkddkkl....
...lkkdkkkkkkkkkkkkttttkkdkkl...
..lkkdkkkkkkkddddddkktttkkdkkl..
..lkkdkkkkkddkkkkkkddkkttkdkkl..
.lkkdkkkkkdkkkkkkkkkkdkkttkdkkl.
.lkkdkkkkdkkkvvvvvvkkkdktttdkkl.
.lkdkkkkdkkvvvvvvvvvvkkdkttkdkl.
lkkdkkkkdkkvvvvvvvvvvkkdkttkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkttdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkttkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
..lkkdkkkkkkkddddddkkkkkkkdkkl..
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
....lkkddkkkkkkkkkkkkkkddkkl....
.....lkkkddkkkkkkkkkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkkkkkkkkkddkkkl.....
....lkkddkkkkkkkkkkkkkkddkkl....
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
..lkkdkkkkkkkddddddkkkkkkkdkkl..
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdkkkkdkkkvvvvvvkkkdkkktdkkl.
.lkdkkkkdkkvvvvvvvvvvkkdkttkdkl.
lkkdkkkkdkkvvvvvvvvvvkkdkttkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkttdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkttkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkttkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkttkdkl
lkdkkkkdkkvvvvkkkkvvvvkkdkttkdkl
lkkdkkkdkkvvvvvvvvvvvvkkdkttdkkl
lkkdkkkkdkkvvvvvvvvvvkkdkttkdkkl
.lkdkkkkdkkvvvvvvvvvvkkdkttkdkl.
.lkkdkkkkdkkkvvvvvvkkkdktttdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkttkdkkl.
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
..lkkdkkkkkkkddddddkkkkkkkdkkl..
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
....lkkddkkkkkkkkkkkkkkddkkl....
.....lkkkddkkkkkkkkkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkkkkkkkkkddkkkl.....
....lkkddkkkkkkkkkkkkkkddkkl....
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
..lkkdkkkkkkkddddddkkkkkkkdkkl..
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkkkkdkkvvvvvvvvvvkkdkttkdkkl
.lkdkkkkdkkvvvvvvvvvvkkdkttkdkl.
.lkkdkkkkdkkkvvvvvvkkkdktttdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkttkdkkl.
..lkkdkkkkkddkkkkkkddkkttkdkkl..
..lkkdkkkkkkkddddddkktttkkdkkl..
...lkkdkkkkkkkkkkkkttttkkdkkl...
....lkkddkkkkkkkktttttkddkkl....
.....lkkkddkkkkkkttkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkkkkkkkkkddkkkl.....
....lkkddkkkkkkkkkkkkkkddkkl....
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
..lkkdkkkkkkkddddddkkkkkkkdkkl..
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
..lkkdkkkttkkddddddkkkkkkkdkkl..
...lkkdkkttttkkkkkkttkkkkdkkl...
....lkkddkttttttttttttkddkkl....
.....lkkkddkkttttttkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkkkkkkkkkddkkkl.....
....lkkddkkkkkkkkkkkkkkddkkl....
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
..lkkdkkkkkkkddddddkkkkkkkdkkl..
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdkkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkdkkkkdkkvvvvvvvvvvkkdkkkkdkl.
lkkdkkkkdkkvvvvvvvvvvkkdkkkkdkkl
lkkdkkkdkkvvvvvvvvvvvvkkdkkkdkkl
lkdkkkkdkkvvvvkkkkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkkkkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkttkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdttkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkttkdkkvvvvvvvvvvkkdkkkkdkkl
.lkdkttkdkkvvvvvvvvvvkkdkkkkdkl.
.lkkdtttkdkkkvvvvvvkkkdkkkkdkkl.
.lkkdkttkkdkkkkkkkkkkdkkkkkdkkl.
..lkkdkttkkddkkkkkkddkkkkkdkkl..
..lkkdkktttkkddddddkkkkkkkdkkl..
...lkkdkkttttkkkkkkkkkkkkdkkl...
....lkkddktttkkkkkkkkkkddkkl....
.....lkkkddkkkkkkkkkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
"""
............llllllll............
.........lllkkkkkkkklll.........
.......llkkkkkddddkkkkkll.......
......lkkkkdddkkkkdddkkkkl......
.....lkkkddkkkkkkkkkkddkkkl.....
....lkkddkkkkkkkkkkkkkkddkkl....
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
..lkkdkkkkkkkddddddkkkkkkkdkkl..
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
.lkkdkttkkdkkkkkkkkkkdkkkkkdkkl.
.lkkdtttkdkkkvvvvvvkkkdkkkkdkkl.
.lkdkttkdkkvvvvvvvvvvkkdkkkkdkl.
lkkdkttkdkkvvvvvvvvvvkkdkkkkdkkl
lkkdttkdkkvvvvvvvvvvvvkkdkkkdkkl
lkdkttkdkkvvvvkkkkvvvvkkdkkkkdkl
lkdkttkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkttkdkkvvvvkwwkvvvvkkdkkkkdkl
lkdkttkdkkvvvvkkkkvvvvkkdkkkkdkl
lkkdttkdkkvvvvvvvvvvvvkkdkkkdkkl
lkkdkttkdkkvvvvvvvvvvkkdkkkkdkkl
.lkdkttkdkkvvvvvvvvvvkkdkkkkdkl.
.lkkdtkkkdkkkvvvvvvkkkdkkkkdkkl.
.lkkdkkkkkdkkkkkkkkkkdkkkkkdkkl.
..lkkdkkkkkddkkkkkkddkkkkkdkkl..
..lkkdkkkkkkkddddddkkkkkkkdkkl..
...lkkdkkkkkkkkkkkkkkkkkkdkkl...
....lkkddkkkkkkkkkkkkkkddkkl....
.....lkkkddkkkkkkkkkkddkkkl.....
......lkkkkdddkkkkdddkkkkl......
.......llkkkkkddddkkkkkll.......
.........lllkkkkkkkklll.........
............llllllll............
""",
    ],
}

# ---------------------------------------------------------------------------
# output
# ---------------------------------------------------------------------------
def parse(name, frames):
    """ASCII frames -> list of row lists; checks size, frame count and palette."""
    w, h, n = EXPECT[name]
    out = []
    for i, art in enumerate(frames):
        rows = art.strip('\n').split('\n')
        assert len(rows) == h and all(len(r) == w for r in rows), f'{name} f{i}: expected {w}x{h}'
        bad = set(''.join(rows)) - set(PALETTE) - {'.'}
        assert not bad, f'{name} f{i}: unknown codes {bad}'
        out.append(rows)
    assert len(out) == n, f'{name}: expected {n} frames, got {len(out)}'
    return out


def runs(rows):
    """Horizontal same-colour runs: (code, x, y, width)."""
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            c = row[x]
            x0 = x
            while x < len(row) and row[x] == c:
                x += 1
            if c != '.':
                yield c, x0, y, x - x0


def rects(rows):
    """Row runs, with identical runs on consecutive rows stacked into one taller rect.
    Every pixel is covered exactly once (no overdraw): (code, x, y, width, height)."""
    out, open_ = [], {}
    for y in range(len(rows) + 1):
        here = {(c, x, w) for c, x, yy, w in runs([rows[y]])} if y < len(rows) else set()
        for key in [k for k in open_ if k not in here]:
            c, x, w = key
            y0 = open_.pop(key)
            out.append((c, x, y0, w, y - y0))
        for key in here:
            open_.setdefault(key, y)
    return sorted(out, key=lambda r: (r[2], r[1]))


def rects_class(rows):
    return ''.join(f'<rect class="{c}" x="{x}" y="{y}" width="{w}" height="{h}"/>' for c, x, y, w, h in rects(rows))


def rects_fill(rows):
    return ''.join(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{PALETTE[c]}"/>' for c, x, y, w, h in rects(rows))


def partial(name, frames):
    h, w = len(frames[0]), len(frames[0][0])
    lines = [f'<svg class="px px--{name} px--n{len(frames)}" viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
             f'shape-rendering="crispEdges" aria-hidden="true" focusable="false">']
    for i, rows in enumerate(frames):
        lines.append(f'<g class="px__f" style="--i:{i}">{rects_class(rows)}</g>')
    lines.append('</svg>')
    return '\n'.join(lines) + '\n'


def preview(rows):
    h, w = len(rows), len(rows[0])
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" shape-rendering="crispEdges">'
            f'<rect width="{w}" height="{h}" fill="{PALETTE["p"]}"/>{rects_fill(rows)}</svg>\n')


SCALE = 4
SHEET_CSS = """
@font-face { font-family: "MS PGothic Pixel"; src: url("../../../static/fonts/mspgothic-pixel.woff2") format("woff2"); }
:root { --bg: #4a3b6b; --deep: #3a2d56; --lilac: #c8c7ff; --teal: #7fffd4; --nyu: #57068c; --k: #241a3a; }
* { box-sizing: border-box; }
html, body { margin: 0; background: var(--bg); }
body { width: 1232px; padding: 32px; color: var(--lilac); font: 16px/1 "MS PGothic Pixel", "MS PGothic", monospace;
       -webkit-font-smoothing: none; }
h1 { margin: 0 0 8px; font-size: 32px; font-weight: 400; color: var(--teal); }
.meta { margin: 0 0 16px; }
.pal { display: flex; flex-wrap: wrap; gap: 16px; margin: 0 0 32px; }
.pal span { display: flex; align-items: center; gap: 8px; }
.pal i { width: 16px; height: 16px; outline: 1px solid var(--lilac); }
.win { margin: 0 0 32px; border: 2px solid var(--lilac); }
.bar { display: flex; justify-content: space-between; padding: 8px; background: var(--nyu); color: #fff; border-bottom: 2px solid var(--lilac); }
.bar b { font-weight: 400; color: var(--teal); }
.frames { display: flex; flex-wrap: wrap; gap: 16px; padding: 16px; }
figure { margin: 0; }
figure svg { display: block; image-rendering: pixelated; outline: 1px dashed rgba(200,199,255,.35); outline-offset: 3px; }
figcaption { margin-top: 8px; color: var(--lilac); }
figure.loop figcaption { color: var(--teal); }
.l { fill: #c8c7ff; } .t { fill: #7fffd4; } .p { fill: #4a3b6b; } .d { fill: #3a2d56; }
.k { fill: #241a3a; } .v { fill: #57068c; } .w { fill: #ffffff; }
/* live loop: the same --i / px--nN contract the site CSS uses */
.loop .px__f { visibility: hidden; animation: var(--kf) var(--dur) infinite;
               animation-delay: calc((var(--i) - var(--n)) * var(--dur) / var(--n)); }
"""


def sheet(sprites):
    kfs = sorted({len(f) for f in sprites.values()})
    css = SHEET_CSS + ''.join(
        f'@keyframes px-step-{n} {{ 0% {{ visibility: visible; }} {100 / n:.4f}% {{ visibility: hidden; }} 100% {{ visibility: hidden; }} }}\n'
        for n in kfs)
    parts = ['<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><title>Pixel art sheet</title>',
             f'<style>{css}</style></head><body>',
             '<h1>arkndjl pixel art</h1>',
             f'<p class="meta">brand/make-pixel-art.py &middot; {len(sprites)} sprites &middot; every frame at {SCALE}&times; '
             '&middot; layouts/partials/px/&lt;name&gt;.html</p><div class="pal">']
    for c, hexv in PALETTE.items():
        parts.append(f'<span><i style="background:{hexv}"></i>{c} {hexv}</span>')
    parts.append('<span><i style="background:transparent"></i>. transparent</span></div>')
    for name, frames in sprites.items():
        h, w = len(frames[0]), len(frames[0][0])
        n = len(frames)
        parts.append(f'<section class="win"><div class="bar"><span>px/{name}.html</span>'
                     f'<span><b>{w}&times;{h}</b> &middot; {n} frames</span></div><div class="frames">')
        for i, rows in enumerate(frames):
            parts.append(f'<figure><svg viewBox="0 0 {w} {h}" width="{w * SCALE}" height="{h * SCALE}" shape-rendering="crispEdges">'
                         f'{rects_class(rows)}</svg><figcaption>f{i}</figcaption></figure>')
        loop = partial(name, frames).replace('\n', '')
        loop = loop.replace(f'width="{w}" height="{h}"', f'width="{w * SCALE}" height="{h * SCALE}"', 1)
        loop = loop.replace('<svg ', f'<svg style="--n:{n};--dur:{n * 0.16:.2f}s;--kf:px-step-{n}" ', 1)
        parts.append(f'<figure class="loop">{loop}<figcaption>loop</figcaption></figure></div></section>')
    parts.append('</body></html>\n')
    return '\n'.join(parts)


def main():
    sprites = {name: parse(name, frames) for name, frames in SPRITES.items()}
    assert set(sprites) == set(EXPECT), set(EXPECT) ^ set(sprites)
    pdir = ROOT / 'layouts/partials/px'
    xdir = ROOT / 'brand/exports/pixelart'
    pdir.mkdir(parents=True, exist_ok=True)
    xdir.mkdir(parents=True, exist_ok=True)
    for old in xdir.glob('*-f*.svg'):
        old.unlink()
    for name, frames in sprites.items():
        (pdir / f'{name}.html').write_text(partial(name, frames))
        for i, rows in enumerate(frames):
            (xdir / f'{name}-f{i}.svg').write_text(preview(rows))
    (xdir / 'sheet.html').write_text(sheet(sprites))
    print('pixel art:', ', '.join(f'{k} {len(v[0][0])}x{len(v[0])}x{len(v)}' for k, v in sprites.items()))
    # contact sheet PNG (Playwright); skipped with a hint if node/playwright are unavailable
    js = ROOT / 'brand/render-pixelart.js'
    if shutil.which('node'):
        r = subprocess.run(['node', str(js)], cwd=ROOT)
        if r.returncode == 0:
            return
    print('sheet.png not rendered: run  NODE_PATH=<dir with playwright> node brand/render-pixelart.js')


if __name__ == '__main__':
    main()
